2024-04-21 21:37:06,428 INFO    MainThread:44904 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-21 21:37:06,428 INFO    MainThread:44904 [wandb_setup.py:_flush():76] Configure stats pid to 44904
2024-04-21 21:37:06,428 INFO    MainThread:44904 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Jonathan\.config\wandb\settings
2024-04-21 21:37:06,428 INFO    MainThread:44904 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Jonathan\Code\wandb-lab\wandb\settings
2024-04-21 21:37:06,428 INFO    MainThread:44904 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-21 21:37:06,428 INFO    MainThread:44904 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'runner.py', 'program_abspath': 'C:\\Users\\Jonathan\\Code\\wandb-lab\\runner.py', 'program': 'C:\\Users\\Jonathan\\Code\\wandb-lab\\runner.py'}
2024-04-21 21:37:06,428 INFO    MainThread:44904 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***', 'base_url': 'https://wandb-lab.jms-lab.com/'}
2024-04-21 21:37:06,428 INFO    MainThread:44904 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-21 21:37:06,428 INFO    MainThread:44904 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-21 21:37:06,429 INFO    MainThread:44904 [wandb_init.py:_log_setup():521] Logging user logs to C:\Users\Jonathan\Code\wandb-lab\wandb\run-20240421_213706-51lgefoo\logs\debug.log
2024-04-21 21:37:06,429 INFO    MainThread:44904 [wandb_init.py:_log_setup():522] Logging internal logs to C:\Users\Jonathan\Code\wandb-lab\wandb\run-20240421_213706-51lgefoo\logs\debug-internal.log
2024-04-21 21:37:06,429 INFO    MainThread:44904 [wandb_init.py:init():561] calling init triggers
2024-04-21 21:37:06,429 INFO    MainThread:44904 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2024-04-21 21:37:06,429 INFO    MainThread:44904 [wandb_init.py:init():611] starting backend
2024-04-21 21:37:06,429 INFO    MainThread:44904 [wandb_init.py:init():615] setting up manager
2024-04-21 21:37:06,430 INFO    MainThread:44904 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-21 21:37:06,432 INFO    MainThread:44904 [wandb_init.py:init():623] backend started and connected
2024-04-21 21:37:06,434 INFO    MainThread:44904 [wandb_init.py:init():715] updated telemetry
2024-04-21 21:37:06,436 INFO    MainThread:44904 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-21 21:37:06,979 INFO    MainThread:44904 [wandb_run.py:_on_init():2357] communicating current version
2024-04-21 21:37:07,437 WARNING MainThread:44904 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\wandb_init.py", line 797, in init
    run._on_init()
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\wandb_run.py", line 2361, in _on_init
    version_result = version_handle.wait(timeout=30)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-04-21 21:37:10,829 WARNING MsgRouterThr:44904 [router.py:message_loop():77] message_loop has been closed
